# Generated by Django 6.0.5 on 2026-05-22 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('year', models.IntegerField(verbose_name='Год написания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена покупки')),
                ('rent_price_2w', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Аренда 2 недели')),
                ('rent_price_1m', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Аренда 1 месяц')),
                ('rent_price_3m', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Аренда 3 месяца')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('buy', 'Покупка'), ('rent_2w', 'Аренда 2 недели'), ('rent_1m', 'Аренда 1 месяц'), ('rent_3m', 'Аренда 3 месяца')], max_length=10, verbose_name='Тип')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Истёк'), ('completed', 'Завершён')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('notified', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
